### ISSUE TITLE
Business Cube 2 integration for NethServer

### ISSUE THREAD

**Issue by federicoballarini** [federicoballarini/nethserver-business#1]
We are completing integration between NethServer and Business Cube 2.
After NTS Informatica review I'm going to push some improvements and then we can go in testing.

**SQL SERVER**

- [x] Explain that "Create database" in Cockpit interface creates a new **empty** database with default collation
- [x] Add a note with complete path of SQLCMD and if it's possible a button to redirect to Terminal
- [x] Check docs

**BUSINESS CUBE 2**

- [x] Explain in a better way that user doesn't have to upload default Business databases, that are already in original rpm
- [x] Add a button to fix permissions of automated installation scripts
- [x] Fix connection string after databases import
- [x] Check installation docs

--

Thanks to Cristian Manoni, Mirto Mengozzi (NTS Informatica), @gsanchietti and @DavidePrincipi

**Comment by federicoballarini** [comment]
I'm going to release the new version of nethserver-mssql. I wait for NTS check to release nethserver-business for testing.

@gsanchietti could you push new nethserver-mssql translations on transifex? Thanks.

**Comment by gsanchietti** [comment]
Translations have been pushed! ;)
